/* 
   Cleaned SQL Script from Log
   Removed duplicates and fixed syntax errors (e.g., 'HIRE' -> 'HIREDATE', 'NAME' -> 'ENAME').
*/
use scott;

-- 1. Basic Select
SELECT * FROM EMP;

-- 2. Subquery: Employee whose Manager is FORD
SELECT * 
FROM EMP 
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'FORD');

-- 3. Subquery: Employee whose Manager is ADAMS
-- (Log contained 'ADAM' and 'ADAMS', ADAMS is the correct Scott schema name)
SELECT ENAME, HIREDATE 
FROM EMP 
WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'ADAMS');

-- 4. Nested Subquery: Employee -> Manager -> Manager (Smith's Manager's Manager)
SELECT ENAME, HIREDATE 
FROM EMP 
WHERE EMPNO = (SELECT MGR FROM EMP 
               WHERE EMPNO = (SELECT MGR FROM EMP WHERE ENAME = 'SMITH'));

-- 5. Subquery: Employees whose Manager is KING
SELECT * 
FROM EMP 
WHERE MGR IN (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');

-- 6. Group By Manager
SELECT * FROM EMP GROUP BY MGR;

-- 7. Self Join: Basic Employee and Manager details
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E2.MGR, E2.ENAME 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO;

-- 8. Self Join: Employee Salary > 2000
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.SAL, E2.MGR, E2.ENAME 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
WHERE E1.SAL > 2000;

-- 9. Self Join: Employee Salary > Manager Salary AND Manager Hired after all Clerks
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.SAL, E2.MGR, E2.ENAME, E2.SAL 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
WHERE E1.SAL > E2.SAL 
AND E2.HIREDATE > ALL (SELECT HIREDATE FROM EMP WHERE JOB = 'CLERK');

-- 10. Self Join: Complex Logic (Sal > Mgr Sal, Hired after NY Dept employees, Mgr Name like 'A')
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.SAL, E2.MGR, E2.ENAME, E2.SAL 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
WHERE E1.SAL > E2.SAL 
  AND E1.HIREDATE > ALL (
      SELECT HIREDATE FROM EMP 
      WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK')
  ) 
  AND E2.ENAME LIKE '%A%';

-- 11. Self Join: Annual Salary Comparison (Sal*12)
SELECT E1.EMPNO, E1.ENAME, E1.JOB, E1.SAL, E2.MGR, E2.ENAME, E2.SAL 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
WHERE E1.SAL*12 > E2.SAL*12 
  AND E1.HIREDATE > ALL (
      SELECT HIREDATE FROM EMP 
      WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK')
  ) 
  AND E2.ENAME LIKE '%A%';

-- 12. 3-Level Hierarchy (Employee -> Manager -> Manager's Manager)
-- (Fixed newlines in aliases for readability)
SELECT 
    E1.EMPNO AS 'EMPLOYEE', E1.ENAME, E1.JOB, E1.MGR, 
    E2.EMPNO AS 'EMPNO (MANAGER)', E2.ENAME, E2.JOB, E2.MGR, 
    E3.EMPNO AS 'EMPNO (MANAGERS MANAGER)', E3.ENAME, E3.JOB, E3.MGR 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
JOIN EMP E3 ON E2.MGR = E3.EMPNO;

-- 13. 3-Level Hierarchy with Salary Logic and Dept Filter
-- (Fixed the logic: "OR '%S%'" is invalid SQL, changed to "OR E1.ENAME LIKE...")
SELECT 
    E1.EMPNO AS 'EMPLOYEE', E1.ENAME, E1.JOB, E1.SAL, E1.MGR, E1.HIREDATE,
    E2.EMPNO AS 'EMPNO (MANAGER)', E2.ENAME, E2.JOB, E1.SAL, E2.MGR, E2.HIREDATE,
    E3.EMPNO AS 'EMPNO (MANAGERS MANAGER)', E3.ENAME, E3.JOB, E1.SAL, E3.MGR, E3.HIREDATE 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
JOIN EMP E3 ON E2.MGR = E3.EMPNO 
WHERE E1.SAL > E2.SAL 
  AND E2.HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'BLAKE') 
  AND (E3.DEPTNO IN (10,30)) 
  AND (E1.ENAME LIKE '%A%' OR E1.ENAME LIKE '%S%')
  AND (E2.ENAME LIKE '%A%' OR E2.ENAME LIKE '%S%')
  AND (E3.ENAME LIKE '%A%' OR E3.ENAME LIKE '%S%');

-- 14. 3-Level Hierarchy including Department Details (Joining 3 EMP and 3 DEPT tables)
SELECT 
    E1.EMPNO AS 'EMPLOYEE', E1.ENAME, E1.JOB, E1.MGR, D1.DEPTNO, D1.DNAME, D1.LOC,
    E2.EMPNO AS 'EMPNO (MANAGER)', E2.ENAME, E2.JOB, E2.MGR, D2.DEPTNO, D2.DNAME, D2.LOC,
    E3.EMPNO AS 'EMPNO (MANAGERS MANAGER)', E3.ENAME, E3.JOB, E3.MGR, D3.DEPTNO, D3.DNAME, D3.LOC 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
JOIN EMP E3 ON E2.MGR = E3.EMPNO 
INNER JOIN DEPT D1 ON E1.DEPTNO = D1.DEPTNO 
INNER JOIN DEPT D2 ON E2.DEPTNO = D2.DEPTNO 
INNER JOIN DEPT D3 ON E3.DEPTNO = D3.DEPTNO;

-- 15. The "Final" Complex Query
-- (Fixed 'HIRE' to 'HIREDATE', 'NAME' to 'ENAME', and aggregated the logic from the last 3 log entries)
SELECT E1.ENAME, E1.HIREDATE 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO 
JOIN EMP E3 ON E2.MGR = E3.EMPNO 
INNER JOIN DEPT D1 ON E1.DEPTNO = D1.DEPTNO 
INNER JOIN DEPT D2 ON E2.DEPTNO = D2.DEPTNO 
WHERE E1.HIREDATE > E2.HIREDATE 
  AND E2.HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'ADAMS') 
  AND E3.SAL > ALL (SELECT SAL FROM EMP WHERE JOB = 'CLERK') 
  AND E1.DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE DNAME = 'RESEARCH') 
  AND E2.DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO') 
  AND E3.DEPTNO = 20;
  

/*
LEFT & RIGHT JOIN
*/

-- QUERY TO DISPLAY DETAILS OF EMPLOYEE & THEIR DEPARTMENTS EVEN IF EMPLOYEE DOESN'T WORK IN ANY DEPARTMENT
SELECT E1.ENAME, E1.JOB, D.DEPTNO, D.DNAME
FROM EMP E1
LEFT JOIN DEPT D ON D.DEPTNO = E1.DEPTNO;

SELECT E1.ENAME, E1.JOB, D.DEPTNO, D.DNAME
FROM EMP E1
RIGHT JOIN DEPT D ON D.DEPTNO = E1.DEPTNO;


/*
FULL OUTER JOIN
*/
-- REMOVE THE DUPLICATE DATA FROM BOTH THE DAT AND KEEP IT SINGLE TIME : FULL OUTER JOIN
SELECT *
FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
UNION
SELECT * 
FROM EMP RIGHT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;


-- KEEP ALL THE DUPLICATE DATA FROM BOTH THE TABLE
SELECT *
FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
UNION ALL
SELECT * 
FROM EMP RIGHT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

select sum(C1.POPULATION)
from CITY C1 LEFT JOIN COUNTRY C2
ON C1.COUNTRYCODE = C2.COUNTRYCODE
WHERE C2.CONTINENT = 'ASIA';
