use SCOTT;

/*
CO-RELATED SUB-QUERY
*/


-- FOURTH HIGHEST DISTINCT SALARY
SELECT E1.SAL
FROM EMP E1
WHERE 3 IN (
	SELECT COUNT(DISTINCT E2.SAL)
	FROM EMP E2
	WHERE E1.SAL < E2.SAL
);
    
-- QUERY TO DISPLAY 5TH MINIMUM
SELECT E1.SAL
FROM EMP E1
WHERE 4 IN (
	SELECT COUNT(DISTINCT E2.SAL)
	FROM EMP E2
    WHERE E1.SAL > E2.SAL
);


-- QUERY TO DISPLAY 4TH AND 5TH MAXIMUM SALARY
SELECT DISTINCT(E1.SAL)
FROM EMP E1
WHERE (SELECT COUNT(DISTINCT E2.SAL)
	FROM EMP E2
    WHERE E1.SAL > E2.SAL
) IN (3,4);


-- QUERY TO DISPLAY FIRST 5 MAXIMUM SALARIES
SELECT DISTINCT(E1.SAL)
FROM EMP E1
WHERE (SELECT COUNT(DISTINCT E2.SAL)
		FROM EMP E2
        WHERE E1.SAL < E2.SAL) IN (0,1,2,3,4)
ORDER BY E1.SAL ASC;

-- QUERY TO DISPLAY 3RD MAX AND 4TH MIN SALARY
SELECT DISTINCT(E1.SAL)
FROM EMP E1
WHERE 2 IN (SELECT COUNT(DISTINCT E2.SAL)
		FROM EMP E2
        WHERE E1.SAL < E2.SAL) OR 3 IN (SELECT COUNT(DISTINCT E2.SAL)
										FROM EMP E2
										WHERE E1.SAL >= E2.SAL);
                                        
-- QUERY TO DISPLAY MAXIMUM SALARY OF EACH DEPT
SELECT DEPTNO, MAX(SAL)
FROM EMP
GROUP BY DEPTNO;

-- QUERY TO DISPLAY 2ND MAXIMUM SALARY OF EACH DEPT
SELECT  E1.DEPTNO, E1.SAL
FROM EMP E1
WHERE 1 IN (SELECT COUNT(DISTINCT E2.SAL)
		FROM EMP E2
        WHERE E1.SAL < E2.SAL AND E1.DEPTNO = E2.DEPTNO);
        
-- QUERY TO DISPLAY DETAILS OF EMPLOYEES WHOSE SALARY IS GREATER THAN
-- THE AVERAGE SALARY OF THE TABLE
SELECT *
FROM EMP
WHERE SAL > (SELECT AVG(SAL) FROM EMP);

-- QUERY TO DISPLAY DETAILS OF EMPLOYEES WHOSE SALARY IS GREATER THAN
-- THE AVERAGE SALARY OF THEIR OWN DEPARTMENT
SELECT E1.*
FROM EMP E1
WHERE E1.SAL > (SELECT AVG(E2.SAL) 
				FROM EMP E2
                WHERE E1.DEPTNO = E2.DEPTNO);

-- QUERY FOR SUB-STR AND SUB-STRING
SELECT SUBSTR("SQL Tutorial", 1) AS ExtractString;
SELECT SUBSTR("SQL Tutorial", 2, 5) AS ExtractString;
SELECT SUBSTR("SQL Tutorial", -5, 5) AS ExtractString;

-- QUERY TO DISPLAY DETAILS OF EMP WHO HAVE EXACTLY TWICE 'L' IN THEIR NAME
use scott;
SELECT *
FROM EMP
WHERE LENGTH(ENAME)-LENGTH(REPLACE(ENAME, 'L', '')) = 2;

SELECT *, SAL + COMM AS TOTAL_SALARY
FROM EMP
WHERE REPLACE(SAL, NULL, 0);


/*
DDL COMMANDS
*/

-- QUERY TO CREATE TABLE UNDER THIS TABLE
CREATE TABLE CUSTOMER(
	CID INT PRIMARY KEY,
    CNAME VARCHAR(20) NOT NULL,
    CNO INT NOT NULL UNIQUE CHECK(LENGTH(CNO)=10) CHECK(CNO > 0),
    ADDRESS VARCHAR(50)
);

-- QUERY
-- RENAMING TABLE
RENAME TABLE CUSTOMER1 TO CUSTOMER;

-- ALTER COLUMN 

SHOW CREATE TABLE CUSTOMER;


CREATE TABLE PRODUCT(
	PID INT PRIMARY KEY,
    PNAME VARCHAR(20) NOT NULL UNIQUE CHECK(LENGTH(PNAME)>0),
    PDESCRIPTION VARCHAR(50),
    CUSTOMER_ID INT,
    foreign key(CUSTOMER_ID) references CUSTOMER(CID)
);

SELECT *
FROM CUSTOMER INNER JOIN PRODUCT
ON CUSTOMER.CID = PRODUCT.CUSTOMER_ID;
