
SCOTT DEFAULT DATABASE IN SQLPLUS
IN WORKBENCH, SAKILA IS THE BY-DEFAULT DATABASE.alter
-- IMPORTING SCOTT HERE --
*/
CREATE DATABASE SCOTT;
USE SCOTT;
DROP TABLE IF EXISTS emp;
CREATE TABLE emp
(
 empno decimal(4,0) NOT NULL,
 ename varchar(10) default NULL,
 job varchar(9) default NULL,
 mgr decimal(4,0) default NULL,
 hiredate date default NULL,
 sal decimal(7,2) default NULL,
 comm decimal(7,2) default NULL,
 deptno decimal(2,0) default NULL
);
DROP TABLE IF EXISTS dept;
CREATE TABLE dept (
 deptno decimal(2,0) default NULL,
 dname varchar(14) default NULL,
 loc varchar(13) default NULL
);
INSERT INTO emp VALUES
('7369','SMITH','CLERK','7902','1980-12-17','800.00',NULL,'20');
INSERT INTO emp VALUES
('7499','ALLEN','SALESMAN','7698','1981-02-20','1600.00','300.00','30');
INSERT INTO emp VALUES
('7521','WARD','SALESMAN','7698','1981-02-22','1250.00','500.00','30');
INSERT INTO emp VALUES 
('7566','JONES','MANAGER','7839','1981-04-02','2975.00',NULL,'20');
INSERT INTO emp VALUES
('7654','MARTIN','SALESMAN','7698','1981-09-28','1250.00','1400.00','30');
INSERT INTO emp VALUES
('7698','BLAKE','MANAGER','7839','1981-05-01','2850.00',NULL,'30');
INSERT INTO emp VALUES
('7782','CLARK','MANAGER','7839','1981-06-09','2450.00',NULL,'10');
INSERT INTO emp VALUES
('7788','SCOTT','ANALYST','7566','1982-12-09','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7839','KING','PRESIDENT',NULL,'1981-11-17','5000.00',NULL,'10');
INSERT INTO emp VALUES
('7844','TURNER','SALESMAN','7698','1981-09-08','1500.00','0.00','30');
INSERT INTO emp VALUES
('7876','ADAMS','CLERK','7788','1983-01-12','1100.00',NULL,'20');
INSERT INTO emp VALUES
('7900','JAMES','CLERK','7698','1981-12-03','950.00',NULL,'30');
INSERT INTO emp VALUES
('7902','FORD','ANALYST','7566','1981-12-03','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7934','MILLER','CLERK','7782','1982-01-23','1300.00',NULL,'10');
INSERT INTO dept VALUES ('10','ACCOUNTING','NEW YORK');
INSERT INTO dept VALUES ('20','RESEARCH','DALLAS');
INSERT INTO dept VALUES ('30','SALES','CHICAGO');
INSERT INTO dept VALUES ('40','OPERATIONS','BOSTON');


/*
IS
IS
IS NOT
*/

SELECT *
FROM EMP
WHERE SAL NOT BETWEEN 1000 AND 3000;

-- WAQTD DETAILS OF THE EMPLOYEES IF EMPLOYEE ARE NOT HIRED IN THE YEAR 81.
SELECT *
FROM EMP
WHERE HIREDATE NOT BETWEEN '01-JAN-1981' AND '31-DEC-1981';

-- WAQTD ENAME, SAL, HIREDATE IF EMPLOYEE IS NOT HIRE AGTER 81 BUT BEFORE 87
SELECT ENAME, SAL, HIREDATE
FROM EMP
WHERE HIREDATE NOT BETWEEN '01-JAN-1982' AND '31-DEC-1986';


-- DETAILS OF EMPLOYEE WHO ARE NOT EARNING COMMISION
SELECT * FROM EMP;
SELECT * FROM EMP
WHERE COMM IS NULL OR COMM = 0;

-- DETAILS OF EMPLIYEE WHO DON'T HAVE REPORTING MANAGER BUT HE IS EARNING MORE THAN
-- 3000 AND LESS THAN 6000
SELECT * FROM EMP
WHERE (MGR IS NULL OR MGR = 0) AND (SAL BETWEEN 3001 AND 5999);

-- WRITE A QUERY TO DISPLAY THE DETAILS OF EMPLOYEE WHO IS NOT EARNING COMMISION 
-- BUT THEY HAVE REPORTING MANAGER
SELECT * FROM EMP
WHERE (COMM = 0 OR COMM IS NULL) AND MGR IS NOT NULL;


/*
LIKE OPERATOR
*/

SELECT ENAME FROM EMP
WHERE ENAME LIKE '%A%';

-- DETAILS OF EMPLOYEE IF THEY HAVE CHARACTER 'MAN' IN THEIR JOB
SELECT *
FROM EMP
WHERE JOB LIKE '%MAN%';

-- DETAILS OF EMPLOYEE IF THEY HAVE CHARACTER 'A' OR CHAR 'S' IN THEIR JOB 
-- AND THEIR SALARY STARTING WITH THE DIGIT OF '50';
SELECT * 
FROM EMP
WHERE (JOB LIKE '%A%' OR JOB LIKE '%S%') AND SAL LIKE '50%';


-- DETAILS OF EMPLOYEE IF THEY ARE HIRED IN THE MONTH OF DECEMBER
SELECT * FROM EMP
WHERE HIREDATE LIKE '_____12%';

SELECT * FROM EMP
WHERE HIREDATE LIKE '%-12-%';

-- DIPLAY DETAILS OF EMPLOYEE IF THEY ARE HIRE IN THE YEAR 1981 AND 4 DIGIT SALARY
SELECT * FROM EMP
WHERE HIREDATE LIKE '1981%' AND SAL LIKE '____.%';

-- QUERY TO DISPLAY NAME , ANNUAL SLARY
-- AND HALF_YERM SALARY ALONG WITH JOB IF THE EMPLOYEES ARE HIRED
-- AFTER 1982 AND BEFORE 89 AND THEY DON'T HAVE 3 DIGIT SALARY
-- BUT THEY ARE WORKING IN DEPNO 10 AND 30 AS A SALESMAN OR ANALYST
-- BUT THEY HAVE A REPORTING MANAGER.

SELECT concat('MR.', ENAME) AS NAME, SAL*12 AS 'ANNUAL SALARY', SAL*6 AS 'HALF_TERM SALARY', JOB
FROM EMP
WHERE
(HIREDATE BETWEEN '1983-01-01' AND '1989-12-31')
AND
(SAL NOT LIKE '___.__')
AND 
(DEPTNO IN (10,30))
AND 
(JOB IN ('SALESMAN', 'ANALYST'))
AND 
(MGR IS NOT NULL);


/*
MULTI-ROW Functions
*/

-- DISPLAY NUMBER OF EMPLOYEES ALONG
-- WITH THEIR MAXIUM SALARY IF THEY ARE WORKING IN DEPTNO 10 0R 30
SELECT COUNT(*), MAX(SAL)
FROM EMP 
WHERE DEPTNO IN (10,30);

-- DISPLAY NUMBER OF EMP WORKING IN DEPT NO 10 IF THEY HAVE REPORTING MANAGER
SELECT COUNT(*) 
FROM EMP
WHERE DEPTNO = 10 AND MGR IS NOT NULL;


/*
GROUP BY
*/
SELECT DEPTNO, COUNT(*) COUNT
FROM EMP
GROUP BY DEPTNO;


-- QUERY TO DISPLAU MAXIUM SALARY OF EMPLOYEE IN EACH DEPARTMENT
SELECT MAX(SAL) AS MAX_SAL, DEPTNO FROM EMP
GROUP BY DEPTNO;

-- QUERY TO DISPLAY NUMBER OF EMP WORKING IN EACH DEPT
-- AND IF THEIR SALARY IS MORE THAN 2000 AND THEY ARE WORKING AS CLERK
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE (SAL < 2000 
AND JOB = "CLERK")
GROUP BY DEPTNO;

-- QUERY TO DISPLAY UNIQUE SALARIES
-- WAY 1
SELECT DISTINCT SAL
FROM EMP;

-- WAY 2
SELECT SAL
FROM EMP
GROUP BY SAL;

-- QUERY TO DISPLAY NUMBER OF TIMES SALARIES HAVE BEEN REPEATED
SELECT COUNT(SAL), SAL
FROM EMP
GROUP BY SAL;

-- QUERY TO DISPLAY TOTAL SALARIES OF EMPLOYEES WORKING IN EACH JOB
-- IF THEIR JOB IS CLERK OR SALESMAN AND THEY ARE HIRED IN THE YEAR OF 1981
SELECT SUM(SAL), JOB, COUNT(JOB)
FROM EMP
WHERE JOB IN ('CLERK', 'SALESMAN') AND (HIREDATE BETWEEN '1981-01-01' AND '1981-12-31')
GROUP BY JOB;

/*
HAVING
*/

-- QUERY TO DISPLAY NUMBER OF EMP WORKING IN EACH DEPT 
-- IF THERE ARE ATLEAST 2 EMPLOYEES WORKING IN EACH DEPT;
SELECT COUNT(*) AS NUMBER, DEPTNO
FROM EMP 
GROUP BY DEPTNO
HAVING COUNT(*) > 2;


-- QUERY TO DISPLAY MAX AND MIN SALARY OF EMP WORKING
-- IN EACH JOB IF MAX SAL OF EACH JOB IS MORE THAN 3000
SELECT MAX(SAL) AS 'MAXIUM SALARY', MIN(SAL) AS 'MINIMUM SALARY', JOB
FROM EMP
GROUP BY JOB
HAVING MAX(SAL) > 3000;

-- QUERY TO DISPLAY TOTAL SALARY OF EMPLOYEES WORKING IN EACH DEPT
-- IF THEIR SALARY IS MORE THAN 2000 AND AVERAGE SALARY NEEDED TO PAY
-- TO THE EMPLOYEE IS LESS THAN 2000.
SELECT SUM(SAL), DEPTNO
FROM EMP
WHERE SAL > 2000
GROUP BY DEPTNO
HAVING AVG(SAL) < 2000;


-- QUERY TO DISPLAY REPEATED SALARY
SELECT SAL, COUNT(SAL)
FROM EMP
GROUP BY SAL
HAVING COUNT(SAL) > 1;

-- QUERY TO DISPLAY MAX SALARY OF EMP WORKING IN EACH JOB
-- IF THEIR JOB IS ANALYST OR CLERK AND THEIR DEPTNO IS 20 BUT
-- THEIR MAX SALARY IS MORE THAN 2000 AND THEOR SALARY IS MORE THAN 1000
SELECT MAX(SAL), JOB
FROM EMP
WHERE JOB IN ('ANALYST', 'CLERK') AND DEPTNO = 20 AND SAL > 1000
GROUP BY JOB
HAVING MAX(SAL) > 2000 ;

/*
SUB-QUERY
*/

-- QUERY TO DISPLAY DETAILS OF EMPLOYEE MORE THAN SMITH;
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = "SMITH");

-- QUERY TO DISPLAY NAME OF THE EMPLOYEES EARNING LESS THAN JONES.
SELECT ENAME, SAL
FROM EMP
WHERE SAL < (SELECT SAL FROM EMP WHERE ENAME = 'JONES');

-- QUERY TO DISPLAY NAME OF THE EMPLOYEES ALONG WITH THE ANNUAL SALARY 
-- WHO ARE HIRED BEFORE JAMES AND EARNING MORE THAN 1000
SELECT ENAME, SAL * 12 AS 'ANNUAL SALARY'
FROM EMP 
WHERE SAL > 1000 AND HIREDATE < (SELECT HIREDATE FROM EMP WHERE ENAME = 'JAMES');

-- QUERY TO DISPALY NAME, SAL, DEPTNO OF THE EMP IF THE EMP
-- EARN MORE THAN 2000 AND WORK IN SAME DEPARTMENT AS JAMES.
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE SAL > 2000 AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'JAMES');

-- QUERY TO DISPLAY DETAILS OF EMP EARNING MORE THAN SMITH BUT LESS THAN KING
SELECT *
FROM EMP
WHERE SAL > (SELECT SAL FROM EMP WHERE ENAME = 'SMITH')
AND 
SAL < (SELECT SAL FROM EMP WHERE ENAME = 'KING');

-- QUERY TO DISPLAY NAME OF EMP WORKING IN SAME DEPT AS JAMES AND EARNING SALARY 
-- MORE THAM ADAMS AND WORKING IN SAME ROLES AS MILLER AND HIRED AFTER MARTIN.
SELECT ENAME
FROM EMP 
WHERE DEPTNO = 		(SELECT DEPTNO FROM EMP WHERE ENAME = 'JAMES')
	AND SAL > 		(SELECT SAL FROM EMP WHERE ENAME = 'ADAMS')
	AND JOB = 		(SELECT JOB FROM EMP WHERE ENAME = 'MILER')
	AND HIREDATE > 	(SELECT HIREDATE FROM EMP WHERE ENAME = 'MARTIN');
