/*
SCOTT DEFAULT DATABASE IN SQLPLUS
IN WORKBENCH, SAKILA IS THE BY-DEFAULT DATABASE.alter
-- IMPORTING SCOTT HERE --
*/

CREATE DATABASE "SCOTT";
USE SCOTT;
DROP TABLE IF EXISTS emp;
CREATE TABLE emp
(
 empno decimal(4,0) NOT NULL,
 ename varchar(10) default NULL,
 job varchar(9) default NULL,
 mgr decimal(4,0) default NULL,
 hiredate date default NULL,
 sal decimal(7,2) default NULL,
 comm decimal(7,2) default NULL,
 deptno decimal(2,0) default NULL
);
DROP TABLE IF EXISTS dept;
CREATE TABLE dept (
 deptno decimal(2,0) default NULL,
 dname varchar(14) default NULL,
 loc varchar(13) default NULL
);
INSERT INTO emp VALUES
('7369','SMITH','CLERK','7902','1980-12-17','800.00',NULL,'20');
INSERT INTO emp VALUES
('7499','ALLEN','SALESMAN','7698','1981-02-20','1600.00','300.00','30');
INSERT INTO emp VALUES
('7521','WARD','SALESMAN','7698','1981-02-22','1250.00','500.00','30');
INSERT INTO emp VALUES 
('7566','JONES','MANAGER','7839','1981-04-02','2975.00',NULL,'20');
INSERT INTO emp VALUES
('7654','MARTIN','SALESMAN','7698','1981-09-28','1250.00','1400.00','30');
INSERT INTO emp VALUES
('7698','BLAKE','MANAGER','7839','1981-05-01','2850.00',NULL,'30');
INSERT INTO emp VALUES
('7782','CLARK','MANAGER','7839','1981-06-09','2450.00',NULL,'10');
INSERT INTO emp VALUES
('7788','SCOTT','ANALYST','7566','1982-12-09','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7839','KING','PRESIDENT',NULL,'1981-11-17','5000.00',NULL,'10');
INSERT INTO emp VALUES
('7844','TURNER','SALESMAN','7698','1981-09-08','1500.00','0.00','30');
INSERT INTO emp VALUES
('7876','ADAMS','CLERK','7788','1983-01-12','1100.00',NULL,'20');
INSERT INTO emp VALUES
('7900','JAMES','CLERK','7698','1981-12-03','950.00',NULL,'30');
INSERT INTO emp VALUES
('7902','FORD','ANALYST','7566','1981-12-03','3000.00',NULL,'20');
INSERT INTO emp VALUES
('7934','MILLER','CLERK','7782','1982-01-23','1300.00',NULL,'10');
INSERT INTO dept VALUES ('10','ACCOUNTING','NEW YORK');
INSERT INTO dept VALUES ('20','RESEARCH','DALLAS');
INSERT INTO dept VALUES ('30','SALES','CHICAGO');
INSERT INTO dept VALUES ('40','OPERATIONS','BOSTON');



-- WAQTD DNAME OF THE EMPLOYEE WHOSE NAME IS MILLER
USE SCOTT;
SELECT * FROM DEPT;

SELECT DEPTNO, DNAME
FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME='MILLER');

-- WAQTD DETAILS OF THE EMPLOYEES WHO ARE WORKING IN THE LOCATION NEW YORK
SELECT * 
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'NEW YORK');

-- WAQTD  ALL THE DETAILS OF THE EMPLOYEES WORKING IN THE SAME DESIGNATION AS MILLER AND WORK IN LOCATION NEW YORK
SELECT * 
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
				FROM DEPT
                WHERE LOC = "NEW YORK") AND JOB = (SELECT JOB FROM EMP
											WHERE ENAME = 'MILLER');
       
                                            
-- WAQTD NNUMBER OF EMP WORKING AS CLERK IN THE SAME DEPTNO AS SMITH AND EARNING MORE THAN KING, HIRED AFTER MARTIN IN THE LOCATION BOSTON
SELECT COUNT(*) COUNT
FROM EMP
WHERE JOB = "CLERK" AND DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH') AND SAL > (SELECT SAL FROM EMP WHERE ENAME = 'KING')
AND HIREDATE > (SELECT HIREDATE FROM EMP WHERE ENAME = 'MARTIN') AND DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'BOSTON');
													
-- QUERY TO DISPLAY DEPARTMENT NAME OF CLERK
SELECT * FROM EMP;

SELECT DNAME
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB = 'CLERK');

-- QUERY TO DISPLAY NUMBER OF EMP WORKING AS CLERK OR SALESMAN EARNING MORE
-- THAN 800 AND WORKING IN THE LOCATION OF NEW YORK OR DALLAS IN EACH DEPARTMENT
SELECT COUNT(*), DEPTNO
FROM EMP
WHERE JOB IN ('CLERK', 'SALESMAN') AND SAL > 800 AND DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC IN ('NEW YORK', 'DALLAS'))
GROUP BY DEPTNO;

-- QUERY TO DISPLAY DETAILS OF EMPLOYEE WHO IS EARNING MAXIMUM SALARY.
SELECT * FROM EMP 
WHERE SAL IN (SELECT MAX(SAL) FROM EMP);

-- QUERY TO DISPLAY 2ND MAXIMUM SALARY
SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP);

-- QUERY TO DISPLAY 3RD MAXIMUM SALARY
SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP
WHERE SAL < (SELECT MAX(SAL) FROM EMP));

-- QUERY TO DISPLAY DETAILS OF EMP WHO IS EARNING 2ND MIN SALARY
SELECT * FROM EMP
WHERE SAL = (SELECT MIN(SAL) 
				FROM EMP 
                WHERE SAL > ( SELECT MIN(SAL) 
								FROM EMP));
                                
-- QUERY TO DISPLAY LOC OF EMP WHO IS EARNING 3RD MAXIMUM SALARY
SELECT LOC 
FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO 
				FROM EMP
                WHERE SAL = (SELECT MAX(SAL) 
							FROM EMP
                            WHERE SAL < (SELECT MAX(SAL) 
										FROM EMP
                                        WHERE SAL < (SELECT MAX(SAL) 
                                        FROM EMP))));
       
/*
SUB-QUERY: ALL OPERATORY
*/
                                        
-- QUERY TO DISPLAY NAME AND HIREDATE OF THE EMP WHO IS EARNING MORE THAN CLERK;
-- WAY 1
SELECT ENAME, HIREDATE
FROM EMP
WHERE SAL > (SELECT MAX(SAL) 
			FROM EMP 
            WHERE JOB = 'CLERK');
            
-- WAY 2
SELECT ENAME, HIREDATE
FROM EMP
WHERE SAL > ALL (SELECT SAL 
			FROM EMP 
            WHERE JOB = 'CLERK');

-- QUERY TO DISPLAY DETAILS OF EMP EARNING LESS THAN SALESMAN AND HIRED AFTER ALL THE CLERK.
SELECT *
FROM EMP
WHERE SAL < ALL (SELECT SAL 
			FROM EMP
            WHERE JOB = 'SALESMAN') AND HIREDATE > ALL (SELECT HIREDATE 
														FROM EMP
                                                        WHERE JOB = 'CLERK');
													
-- QUERY TO DISPLAY DETAILS OF EMP  EARNING MORE THAN THE EMPLOYEE 
-- WHO IS HAVING CHARACTER 'A' IN HIS NAME AND EARNING LESS THAN THE
-- EMPLOYEE WHO IS WORKING IN THE LOCATION OF CHICAGO.
SELECT *
FROM EMP
WHERE SAL > ALL (SELECT SAL
				FROM EMP
                WHERE ENAME LIKE '%A%') AND SAL < ALL (SELECT SAL
														FROM EMP
                                                        WHERE DEPTNO IN (SELECT DEPTNO 
																		FROM DEPT 
                                                                        WHERE LOC = 'CHICAGO'));
                                                                        
/*
SUB-QUERY: ANY OPERATOR
*/
SELECT *
FROM EMP
WHERE SAL > ANY (SELECT SAL
				FROM EMP
                WHERE JOB = 'CLERK');
                
-- QUERY TO DISPLAY NAME  AND HIREDATE AND ANNUAL SALARY
-- OF THE EMPLOYEE IF HIS SALARY IS GREATER THAN ANY ONE OF CLERK'S
-- ANNUAL SALARY BUT THOSE EMPLOYEES ARE HIRED AFTER MANAGERS.
SELECT ENAME, HIREDATE, SAL * 12 AS 'ANNUAL SALARY'
FROM EMP
WHERE SAL*12 > ANY (SELECT SAL*12
				FROM EMP
                WHERE JOB = 'CLERK') AND HIREDATE > ALL (SELECT HIREDATE 
													FROM EMP
                                                    WHERE JOB = 'MANAGER');
                                                    
-- QUERY TO DISPLAY NAME, HALF TERM SALARY OF EMP WHO IS 
-- HIRED AFTER ADAMS AND EARNING LESS THAN THE EMP WHO
-- IS HAVING CHARACTER 'MAN' IN HIS JOB AND THEY ARE HIRED
-- AFTER ATLEAST A SAMESMAN IF THEIR SALARY IS IN THE RANGE OF 1000 TO 5000;
SELECT ENAME, SAL * 6 AS 'HALF TERM SAL'
FROM EMP
WHERE HIREDATE > (SELECT HIREDATE
					FROM EMP
                    WHERE ENAME = 'ADAMS') AND SAL < ALL (SELECT SAL
														FROM EMP	
                                                        WHERE JOB LIKE '%MAN%') AND HIREDATE > ANY (SELECT HIREDATE 
																									FROM EMP
                                                                                                    WHERE JOB = 'SALESMAN') AND SAL BETWEEN 1000 AND 5000;

/*
JOINS
*/
SELECT * 
FROM EMP CROSS JOIN DEPT;

/*
INNER JOIN
*/

-- QUERY TO DISPLAY DETAILS OF EMPLOYEES AND THEIR DEPARTMENTS
-- IF THE EMPLOYEES ARE EARNING MORE THAN 3000.
SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE SAL > 3000;

-- QUERY TO DISPLAY DETAILS OF DEPARTMENT ALONG WITH THE EMPLOYEE
-- NAMES IF EMPLOYEES ARE WORKING IN THE LOCATION OF CHICAGO AND
-- THEY ARE HIRED AFTER CLERK 
SELECT DEPT.*, ENAME
FROM EMP INNER JOIN DEPT
ON DEPT.DEPTNO = EMP.DEPTNO
WHERE DEPT.LOC = 'CHICAGO' 
AND EMP.HIREDATE > ALL (SELECT HIREDATE
					FROM EMP
                    WHERE JOB = 'CLERK');
                    
-- QUERY TO DISPLAY NUMBER OF EMPLOYEES WORKING IN EACH DEPARTMENT
-- IF THEIR MAXIMUM SALARY IS MORE THAN 2000 AND THEIR LOC IS NEW YORK
-- OR CHICAGO AND THEY ARE HIREDD AFTER THE EMPLOYEE WHO IS NOT EARNING
-- COMMISSION
SELECT COUNT(*) COUNT
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO
WHERE DEPT.LOC IN ('NEW YORK', 'CHICAGO') AND HIREDATE > ALL (SELECT HIREDATE 
																FROM EMP 
                                                                WHERE COMM IS NULL OR COMM = 0)
GROUP BY EMP.DEPTNO
HAVING MAX(SAL) > 2000;

/*
EMPLOYEE MANAGER RELATIONSHIP
*/

-- QUERY TO DISPLAY DETAILS OF FORD'S MANAGER
SELECT *
FROM EMP
WHERE EMPNO = (SELECT MGR 
				FROM EMP 
                WHERE ENAME = 'FORD');
                
-- QUERY TO DISPLAY NAME AND HIREDATE OOF ADAMS'S MANAGER.
SELECT ENAME, HIREDATE
FROM EMP
WHERE EMPNO = (SELECT MGR
				FROM EMP
                WHERE ENAME = 'ADAMS');
                
-- QUERY TO DISPLAY NAME AND HIREDATE OF SMITH'S MANAGER'S MANAGER
SELECT ENAME, HIREDATE
FROM EMP
WHERE EMPNO = (SELECT MGR 
				FROM EMP
				WHERE EMPNO = (SELECT MGR 
								FROM EMP
								WHERE ENAME = 'SMITH'));

-- QUERY TO DISPLAY THE DETAILS OF EMPLOYEE REPORTING TO KING
SELECT *
FROM EMP 
WHERE MGR IN (SELECT EMPNO 
				FROM EMP
                WHERE ENAME = 'KING');
